import { Todo } from '../models/todo.model';
import { generateUniqueId } from './id-generation-util';

export const INITIAL_TODOS: Todo[] = [
  { id: generateUniqueId(), content: "Lorem ipsum dolor sit amet.", state: "done" },
  { id: generateUniqueId(), content: "Consectetur adipiscing elit.", state: "open" },
  { id: generateUniqueId(), content: "Sed do eiusmod tempor.", state: "open" },
  { id: generateUniqueId(), content: "Incididunt ut labore et dolore.", state: "done" },
  { id: generateUniqueId(), content: "Magna aliqua ut enim ad minim.", state: "open" },
  { id: generateUniqueId(), content: "Veniam quis nostrud exercitat.", state: "open" },
  { id: generateUniqueId(), content: "Ullamco laboris nisi ut aliquip.", state: "open" },
  { id: generateUniqueId(), content: "Ex ea commodo consequat.", state: "done" },
  { id: generateUniqueId(), content: "Duis aute irure dolor in reprehen.", state: "open" },
  { id: generateUniqueId(), content: "In voluptate velit esse cillum.", state: "open" },
  { id: generateUniqueId(), content: "Dolore eu fugiat nulla pariatur.", state: "done" },
  { id: generateUniqueId(), content: "Excepteur sint occaecat cupid.", state: "open" },
  { id: generateUniqueId(), content: "Non proident sunt in culpa qui.", state: "done" },
  { id: generateUniqueId(), content: "Officia deserunt mollit anim id.", state: "open" },
  { id: generateUniqueId(), content: "Est laborum accumsan in nisl.", state: "done" },
  { id: generateUniqueId(), content: "Nisi scelerisque eu ultrices vita.", state: "open" },
  { id: generateUniqueId(), content: "Auctor eu mattis nunc sed blandit.", state: "done" },
  { id: generateUniqueId(), content: "Libero volutpat sed nulla facilisi.", state: "open" },
  { id: generateUniqueId(), content: "Morbi tempus iaculis urna id volu.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat lacus purus semper eget.", state: "open" },
  { id: generateUniqueId(), content: "Duis at tellus at urna quis eleif.", state: "done" },
  { id: generateUniqueId(), content: "Quam adipiscing vitae proin sagitt.", state: "open" },
  { id: generateUniqueId(), content: "Nisl rhoncus mattis rhoncus urna.", state: "open" },
  { id: generateUniqueId(), content: "Ultrices sed tristique risus.", state: "done" },
  { id: generateUniqueId(), content: "Senectus et netus et malesuada.", state: "open" },
  { id: generateUniqueId(), content: "Fames ac turpis egestas integer.", state: "done" },
  { id: generateUniqueId(), content: "Eget aliquet nibh praesent.", state: "open" },
  { id: generateUniqueId(), content: "Tristique magna sit amet cursus.", state: "open" },
  { id: generateUniqueId(), content: "Sit amet dictum sit amet.", state: "done" },
  { id: generateUniqueId(), content: "Justo donec enim diam vulputate.", state: "open" },
  { id: generateUniqueId(), content: "Ullamcorper morbi tincidunt.", state: "open" },
  { id: generateUniqueId(), content: "Ornare massa eget egestas.", state: "done" },
  { id: generateUniqueId(), content: "Sed tempus urna et pharetra.", state: "open" },
  { id: generateUniqueId(), content: "Blandit aliquam etiam erat.", state: "done" },
  { id: generateUniqueId(), content: "Velit euismod in pellentesque massa.", state: "open" },
  { id: generateUniqueId(), content: "Pellentesque adipiscing commodo.", state: "open" },
  { id: generateUniqueId(), content: "Elit at imperdiet dui accumsan.", state: "open" },
  { id: generateUniqueId(), content: "Sit amet nulla facilisi morbi.", state: "done" },
  { id: generateUniqueId(), content: "Tempus iaculis urna id volu.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat lacus laoreet non.", state: "open" },
  { id: generateUniqueId(), content: "Curabitur vitae nunc sed velit.", state: "done" },
  { id: generateUniqueId(), content: "Velit sed ullamcorper morbi.", state: "open" },
  { id: generateUniqueId(), content: "Tincidunt ornare massa eget.", state: "done" },
  { id: generateUniqueId(), content: "Egestas purus viverra accumsan.", state: "open" },
  { id: generateUniqueId(), content: "In nisl nisi scelerisque.", state: "open" },
  { id: generateUniqueId(), content: "Eu ultrices vitae auctor eu.", state: "done" },
  { id: generateUniqueId(), content: "Mattis nunc sed blandit libero.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat sed nulla facilisi.", state: "done" },
  { id: generateUniqueId(), content: "Morbi tempus iaculis urna id.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat lacus purus semper.", state: "open" },
  { id: generateUniqueId(), content: "Eget duis at tellus at urna.", state: "open" },
  { id: generateUniqueId(), content: "Quis eleifend quam adipiscing.", state: "done" },
  { id: generateUniqueId(), content: "Vitae proin sagittis nisl rhon.", state: "open" },
  { id: generateUniqueId(), content: "Rhoncus urna ultrices sed tristi.", state: "done" },
  { id: generateUniqueId(), content: "Tristique risus senectus et netu.", state: "open" },
  { id: generateUniqueId(), content: "Et malesuada fames ac turpis.", state: "open" },
  { id: generateUniqueId(), content: "Egestas integer eget aliquet.", state: "done" },
  { id: generateUniqueId(), content: "Nibh praesent tristique magna.", state: "open" },
  { id: generateUniqueId(), content: "Sit amet cursus sit amet dictu.", state: "done" },
  { id: generateUniqueId(), content: "Dictum sit amet justo donec.", state: "open" },
  { id: generateUniqueId(), content: "Enim diam vulputate ullamcorp.", state: "done" },
  { id: generateUniqueId(), content: "Morbi tincidunt ornare massa.", state: "open" },
  { id: generateUniqueId(), content: "Eget egestas purus viverra.", state: "open" },
  { id: generateUniqueId(), content: "Accumsan in nisl nisi scelerisq.", state: "done" },
  { id: generateUniqueId(), content: "Eu ultrices vitae auctor eu ma.", state: "open" },
  { id: generateUniqueId(), content: "Mattis nunc sed blandit libero v.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat sed nulla facilisi mor.", state: "done" },
  { id: generateUniqueId(), content: "Tempus iaculis urna id volu la.", state: "open" },
  { id: generateUniqueId(), content: "Lac purus semper eget duis at t.", state: "done" },
  { id: generateUniqueId(), content: "Tellus at urna quis eleifend q.", state: "open" },
  { id: generateUniqueId(), content: "Quam adipiscing vitae proin sag.", state: "open" },
  { id: generateUniqueId(), content: "Sagittis nisl rhoncus mattis rhon.", state: "done" },
  { id: generateUniqueId(), content: "Rhoncus urna ultrices sed tristiq.", state: "open" },
  { id: generateUniqueId(), content: "Tristique risus senectus et net.", state: "done" },
  { id: generateUniqueId(), content: "Et malesuada fames ac turpis eg.", state: "open" },
  { id: generateUniqueId(), content: "Egestas integer eget aliquet ni.", state: "open" },
  { id: generateUniqueId(), content: "Nibh praesent tristique magna s.", state: "open" },
  { id: generateUniqueId(), content: "Sit amet cursus sit amet dictu s.", state: "done" },
  { id: generateUniqueId(), content: "Dictum sit amet justo donec en.", state: "open" },
  { id: generateUniqueId(), content: "Enim diam vulputate ullamcorp m.", state: "done" },
  { id: generateUniqueId(), content: "Morbi tincidunt ornare massa eg.", state: "open" },
  { id: generateUniqueId(), content: "Eget egestas purus viverra acc.", state: "open" },
  { id: generateUniqueId(), content: "Accumsan in nisl nisi sceleris.", state: "done" },
  { id: generateUniqueId(), content: "Eu ultrices vitae auctor eu mat.", state: "open" },
  { id: generateUniqueId(), content: "Mattis nunc sed blandit libero vo.", state: "done" },
  { id: generateUniqueId(), content: "Volutpat sed nulla facilisi mo.", state: "open" },
  { id: generateUniqueId(), content: "Morbi tempus iaculis urna id vo.", state: "open" },
  { id: generateUniqueId(), content: "Volutpat lacus purus semper eg.", state: "done" },
  { id: generateUniqueId(), content: "Eget duis at tellus at urna qu.", state: "open" },
  { id: generateUniqueId(), content: "Quis eleifend quam adipiscing v.", state: "open" },
  { id: generateUniqueId(), content: "Vitae proin sagittis nisl rhonc.", state: "done" },
  { id: generateUniqueId(), content: "Rhoncus mattis rhoncus urna ult.", state: "open" },
  { id: generateUniqueId(), content: "Ultrices sed tristique risus sen.", state: "done" },
  { id: generateUniqueId(), content: "Senectus et netus et malesuada f.", state: "open" },
  { id: generateUniqueId(), content: "Fames ac turpis egestas integer e.", state: "open" },
  { id: generateUniqueId(), content: "Eget aliquet nibh praesent tris.", state: "done" },
  { id: generateUniqueId(), content: "Tristique magna sit amet cursus s.", state: "open" },
  { id: generateUniqueId(), content: "Sit amet dictum sit amet justo d.", state: "open" },
  { id: generateUniqueId(), content: "Donec enim diam vulputate ullamc.", state: "done" },
  { id: generateUniqueId(), content: "Ullamcorper morbi tincidunt orn.", state: "open" },
  { id: generateUniqueId(), content: "Ornare massa eget egestas purus.", state: "open" },
  { id: generateUniqueId(), content: "Purus viverra accumsan in nisl.", state: "done" },
  { id: generateUniqueId(), content: "Nisi scelerisque eu ultrices.", state: "open" },
];