import { Todo } from '../models/todo.model';
import { generateUniqueId } from './id-generation-util';

export const INITIAL_TODOS: Todo[] = [
  { uuid: generateUniqueId(), index: 1, content: "Lorem ipsum dolor sit amet.", state: "done" },
  { uuid: generateUniqueId(), index: 2, content: "Consectetur adipiscing elit.", state: "open" },
  { uuid: generateUniqueId(), index: 3, content: "Lorem Ipsum #1", state: "open" },
  { uuid: generateUniqueId(), index: 4, content: "Incididunt ut labore et dolore.", state: "done" },
  { uuid: generateUniqueId(), index: 5, content: "Magna aliqua ut enim ad minim.", state: "open" },
  { uuid: generateUniqueId(), index: 6, content: "Lorem Ipsum #2", state: "open" },
  { uuid: generateUniqueId(), index: 7, content: "Ullamco laboris nisi ut aliquip.", state: "open" },
  { uuid: generateUniqueId(), index: 8, content: "Ex ea commodo consequat.", state: "done" },
  { uuid: generateUniqueId(), index: 9, content: "Lorem Ipsum #3", state: "done" },
  { uuid: generateUniqueId(), index: 10, content: "In voluptate velit esse cillum.", state: "open" },
  { uuid: generateUniqueId(), index: 11, content: "Dolore eu fugiat nulla pariatur.", state: "done" },
  { uuid: generateUniqueId(), index: 12, content: "Lorem Ipsum #4", state: "open" },
  { uuid: generateUniqueId(), index: 13, content: "Non proident sunt in culpa qui.", state: "done" },
  { uuid: generateUniqueId(), index: 14, content: "Officia deserunt mollit anim id.", state: "open" },
  { uuid: generateUniqueId(), index: 15, content: "Lorem Ipsum #5", state: "done" },
  { uuid: generateUniqueId(), index: 16, content: "Nisi scelerisque eu ultrices vita.", state: "open" },
  { uuid: generateUniqueId(), index: 17, content: "Auctor eu mattis nunc sed blandit.", state: "done" },
  { uuid: generateUniqueId(), index: 18, content: "Lorem Ipsum #6", state: "done" },
  { uuid: generateUniqueId(), index: 19, content: "Morbi tempus iaculis urna id volu.", state: "open" },
  { uuid: generateUniqueId(), index: 20, content: "Volutpat lacus purus semper eget.", state: "open" },
  { uuid: generateUniqueId(), index: 21, content: "Lorem Ipsum #7", state: "done" },
  { uuid: generateUniqueId(), index: 22, content: "Quam adipiscing vitae proin sagitt.", state: "open" },
  { uuid: generateUniqueId(), index: 23, content: "Nisl rhoncus mattis rhoncus urna.", state: "open" },
  { uuid: generateUniqueId(), index: 24, content: "Lorem Ipsum #8", state: "done" },
  { uuid: generateUniqueId(), index: 25, content: "Senectus et netus et malesuada.", state: "open" },
  { uuid: generateUniqueId(), index: 26, content: "Fames ac turpis egestas integer.", state: "done" },
  { uuid: generateUniqueId(), index: 27, content: "Lorem Ipsum #9", state: "open" },
  { uuid: generateUniqueId(), index: 28, content: "Tristique magna sit amet cursus.", state: "open" },
  { uuid: generateUniqueId(), index: 29, content: "Sit amet dictum sit amet.", state: "done" },
  { uuid: generateUniqueId(), index: 30, content: "Lorem Ipsum #10", state: "open" },
  { uuid: generateUniqueId(), index: 31, content: "Ullamcorper morbi tincidunt.", state: "open" },
  { uuid: generateUniqueId(), index: 32, content: "Ornare massa eget egestas.", state: "done" },
  { uuid: generateUniqueId(), index: 33, content: "Lorem Ipsum #11", state: "open" },
  { uuid: generateUniqueId(), index: 34, content: "Blandit aliquam etiam erat.", state: "done" },
  { uuid: generateUniqueId(), index: 35, content: "Velit euismod in pellentesque massa.", state: "open" },
  { uuid: generateUniqueId(), index: 36, content: "Lorem Ipsum #12", state: "open" },
  { uuid: generateUniqueId(), index: 37, content: "Elit at imperdiet dui accumsan.", state: "open" },
  { uuid: generateUniqueId(), index: 38, content: "Sit amet nulla facilisi morbi.", state: "done" },
  { uuid: generateUniqueId(), index: 39, content: "Lorem Ipsum #13", state: "open" },
  { uuid: generateUniqueId(), index: 40, content: "Volutpat lacus laoreet non.", state: "open" },
  { uuid: generateUniqueId(), index: 41, content: "Curabitur vitae nunc sed velit.", state: "done" },
  { uuid: generateUniqueId(), index: 42, content: "Lorem Ipsum #14", state: "open" },
  { uuid: generateUniqueId(), index: 43, content: "Tincidunt ornare massa eget.", state: "done" },
  { uuid: generateUniqueId(), index: 44, content: "Egestas purus viverra accumsan.", state: "open" },
  { uuid: generateUniqueId(), index: 45, content: "Lorem Ipsum #15", state: "open" },
  { uuid: generateUniqueId(), index: 46, content: "Eu ultrices vitae auctor eu.", state: "done" },
  { uuid: generateUniqueId(), index: 47, content: "Mattis nunc sed blandit libero.", state: "open" },
  { uuid: generateUniqueId(), index: 48, content: "Lorem Ipsum #16", state: "done" },
  { uuid: generateUniqueId(), index: 49, content: "Morbi tempus iaculis urna id.", state: "open" },
  { uuid: generateUniqueId(), index: 50, content: "Volutpat lacus purus semper.", state: "open" },
  { uuid: generateUniqueId(), index: 51, content: "Lorem Ipsum #17", state: "open" },
  { uuid: generateUniqueId(), index: 52, content: "Quis eleifend quam adipiscing.", state: "done" },
  { uuid: generateUniqueId(), index: 53, content: "Vitae proin sagittis nisl rhon.", state: "open" },
  { uuid: generateUniqueId(), index: 54, content: "Lorem Ipsum #18", state: "done" },
  { uuid: generateUniqueId(), index: 55, content: "Tristique risus senectus et netu.", state: "open" },
  { uuid: generateUniqueId(), index: 56, content: "Et malesuada fames ac turpis.", state: "open" },
  { uuid: generateUniqueId(), index: 57, content: "Lorem Ipsum #19", state: "done" },
  { uuid: generateUniqueId(), index: 58, content: "Nibh praesent tristique magna.", state: "open" },
  { uuid: generateUniqueId(), index: 59, content: "Sit amet cursus sit amet dictu.", state: "done" },
  { uuid: generateUniqueId(), index: 60, content: "Lorem Ipsum #20", state: "open" },
  { uuid: generateUniqueId(), index: 61, content: "Enim diam vulputate ullamcorp.", state: "done" },
  { uuid: generateUniqueId(), index: 62, content: "Morbi tincidunt ornare massa.", state: "open" },
  { uuid: generateUniqueId(), index: 63, content: "Lorem Ipsum #21", state: "open" },
  { uuid: generateUniqueId(), index: 64, content: "Accumsan in nisl nisi scelerisq.", state: "done" },
  { uuid: generateUniqueId(), index: 65, content: "Eu ultrices vitae auctor eu ma.", state: "open" },
  { uuid: generateUniqueId(), index: 66, content: "Lorem Ipsum #22", state: "open" },
  { uuid: generateUniqueId(), index: 67, content: "Volutpat sed nulla facilisi mor.", state: "done" },
  { uuid: generateUniqueId(), index: 68, content: "Tempus iaculis urna id volu la.", state: "open" },
  { uuid: generateUniqueId(), index: 69, content: "Lorem Ipsum #23", state: "done" },
  { uuid: generateUniqueId(), index: 70, content: "Tellus at urna quis eleifend q.", state: "open" },
  { uuid: generateUniqueId(), index: 71, content: "Quam adipiscing vitae proin sag.", state: "open" },
  { uuid: generateUniqueId(), index: 72, content: "Lorem Ipsum #24", state: "done" },
  { uuid: generateUniqueId(), index: 73, content: "Rhoncus urna ultrices sed tristiq.", state: "open" },
  { uuid: generateUniqueId(), index: 74, content: "Tristique risus senectus et net.", state: "done" },
  { uuid: generateUniqueId(), index: 75, content: "Lorem Ipsum #25", state: "open" },
  { uuid: generateUniqueId(), index: 76, content: "Egestas integer eget aliquet ni.", state: "open" },
  { uuid: generateUniqueId(), index: 77, content: "Nibh praesent tristique magna s.", state: "open" },
  { uuid: generateUniqueId(), index: 78, content: "Lorem Ipsum #26", state: "done" },
  { uuid: generateUniqueId(), index: 79, content: "Dictum sit amet justo donec en.", state: "open" },
  { uuid: generateUniqueId(), index: 80, content: "Enim diam vulputate ullamcorp m.", state: "done" },
  { uuid: generateUniqueId(), index: 81, content: "Lorem Ipsum #27", state: "open" },
  { uuid: generateUniqueId(), index: 82, content: "Eget egestas purus viverra acc.", state: "open" },
  { uuid: generateUniqueId(), index: 83, content: "Accumsan in nisl nisi sceleris.", state: "done" },
  { uuid: generateUniqueId(), index: 84, content: "Lorem Ipsum #28", state: "open" },
  { uuid: generateUniqueId(), index: 85, content: "Mattis nunc sed blandit libero vo.", state: "done" },
  { uuid: generateUniqueId(), index: 86, content: "Volutpat sed nulla facilisi mo.", state: "open" },
  { uuid: generateUniqueId(), index: 87, content: "Lorem Ipsum #29", state: "open" },
  { uuid: generateUniqueId(), index: 88, content: "Volutpat lacus purus semper eg.", state: "done" },
  { uuid: generateUniqueId(), index: 89, content: "Eget duis at tellus at urna qu.", state: "open" },
  { uuid: generateUniqueId(), index: 90, content: "Lorem Ipsum #30", state: "open" },
  { uuid: generateUniqueId(), index: 91, content: "Vitae proin sagittis nisl rhonc.", state: "done" },
  { uuid: generateUniqueId(), index: 92, content: "Rhoncus mattis rhoncus urna ult.", state: "open" },
  { uuid: generateUniqueId(), index: 93, content: "Ultrices sed tristique risus sen.", state: "done" },
  { uuid: generateUniqueId(), index: 94, content: "Senectus et netus et malesuada f.", state: "open" },
  { uuid: generateUniqueId(), index: 95, content: "Fames ac turpis egestas integer e.", state: "open" },
  { uuid: generateUniqueId(), index: 96, content: "Eget aliquet nibh praesent tris.", state: "done" },
  { uuid: generateUniqueId(), index: 97, content: "Tristique magna sit amet cursus s.", state: "open" },
  { uuid: generateUniqueId(), index: 98, content: "Sit amet dictum sit amet justo d.", state: "open" },
  { uuid: generateUniqueId(), index: 99, content: "Donec enim diam vulputate ullamc.", state: "done" },
  { uuid: generateUniqueId(), index: 100, content: "Ullamcorper morbi tincidunt orn.", state: "open" },
];
